### ISSUE TITLE
Write Header component with conditional nav

### ISSUE THREAD

**Issue by emmazart** [MNlegion/A-Dish-A-Day#4]
Landing page nav:
- Logo/standard branding
- Login
- Search by Protein
- View All
- About

Standard page nav:
- Logo/standard branding
- Conditional login/logout
- Search Recipes
- Your Favorites

**Comment by MNlegion** [comment]
- Working on navigation panel and styling
- logo import is ready to get set up (just need the logo)
- have scripting for various navigation routes ready

Still Need

- working on styling for the profile avatar dropdown 
- this avatar dropdown also contains login/logout, dashboard, and profile route ready currently (do we want to try and incorporate this?)

**Comment by emmazart** [comment]
Finished the routing for all the tabs currently in the nav bar (in branch feature/react-routing)
